export const postConstants = {
    GET_POSTS_REQUEST: 'GET_POSTS_REQUEST',
    GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',

    GET_POST_BY_ID_REQUEST: 'GET_POST_BY_ID_REQUEST',
    GET_POST_BY_ID_SUCCESS: 'GET_POST_BY_ID_SUCCESS',

    COMMENT_POST: 'COMMENT_POST',

    GET_POSTS_BY_SEARCH_REQUEST: 'GET_POSTS_BY_SEARCH_REQUEST',
    GET_POSTS_BY_SEARCH_SUCCESS: 'GET_POSTS_BY_SEARCH_SUCCESS',

    CREATE_POSTS_REQUEST: 'CREATE_POSTS_REQUEST',
    CREATE_POSTS_SUCCESS: 'CREATE_POSTS_SUCCESS',

    UPDATE_POSTS_REQUEST: 'UPDATE_POSTS_REQUEST',
    UPDATE_POSTS_SUCCESS: 'UPDATE_POSTS_SUCCESS',

    DELETE_POSTS_REQUEST: 'DELETE_POSTS_REQUEST',
    DELETE_POSTS_SUCCESS: 'DELETE_POSTS_SUCCESS',

    LIKE_POSTS_SUCCESS: 'LIKE_POSTS_SUCCESS',
}

export const authConstant = {
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP',
    LOGOUT: 'LOGOUT'
}